In [1]:
import os
import numpy as np
import pandas as pd

/Users/anwesh/opt/anaconda3/envs/tf/lib/python3.9/site-packages/pandas/core/arrays/masked.py:60: UserWarning: Pandas requires version '1.3.6' or newer of 'bottleneck' (version '1.3.5' currently installed).
  from pandas.core import (

In [2]:
data_dir = '/Users/anwesh/code/IIT-Projects/Adversarial-Attacks-and-Defenses-in-In-Vehicular-Networks/Smart Attack Algorithm/data/Car Hacking Dataset/'

fuzzy_data_path = os.path.join(data_dir, 'Fuzzy_dataset.csv')
gear_data_path = os.path.join(data_dir, 'gear_dataset.csv')
rpm_data_path = os.path.join(data_dir, 'RPM_dataset.csv')

In [5]:
def shift_columns(df):
    
    for dlc in [2,5,6]:

        df.loc[df['DLC'] == dlc, df.columns[3:]] = df.loc[df['DLC'] == dlc, df.columns[3:]].shift(periods=8-dlc, axis='columns', fill_value='00')

    return df
    
def hex_to_dec(x):
        return int(str(x), 16)

def transform_data(data):

    data['ID'] = data['ID'].apply(hex_to_dec)
    data['Payload'] = data['Payload'].apply(hex_to_dec)

    return data    

def read_ch_data(data_path):
    
    columns = ['Timestamp','ID', 'DLC', 'data0', 'data1', 'data2', 'data3', 'data4', 
           'data5', 'data6', 'data7', 'label']
    
    data = pd.read_csv(data_path, names = columns)

    data = shift_columns(data)
    
    ##Replacing all NaNs with '00' 
    data = data.replace(np.NaN, '00')
    
    ##Joining all data columns to put all data in one column
    data_cols = ['data0', 'data1', 'data2', 'data3', 'data4', 'data5', 'data6', 'data7']
    
    ##The data column is in hexadecimal
    data['Payload'] = data[data_cols].apply(''.join, axis=1)
    data.drop(columns = data_cols, inplace = True, axis = 1)

    data = transform_data(data)
        
    data = data[['Timestamp', 'ID','DLC','Payload','label']]
    data['label'].replace({'R' : 0, 'T' : 1}, inplace = True)
    
    return data

print("Preprocessing Car Hacking Fuzzy Dataset")
ch_fuzzy_data = read_ch_data(fuzzy_data_path)
print("Preprocessing Car Hacking Gear Spoofing Dataset")
ch_gear_data = read_ch_data(gear_data_path)
print("Preprocessing Car Hacking RPM Spoofing Dataset")
ch_rpm_data = read_ch_data(rpm_data_path)

Preprocessing Car Hacking Fuzzy Dataset

/var/folders/pw/3vr89zzj1xvbzvtk1yfz9kkc0000gn/T/ipykernel_47040/2115221741.py:41: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data['label'].replace({'R' : 0, 'T' : 1}, inplace = True)
/var/folders/pw/3vr89zzj1xvbzvtk1yfz9kkc0000gn/T/ipykernel_47040/2115221741.py:41: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  data['label'].replace({'R' : 0, 'T' : 1}, inplace = True)

Preprocessing Car Hacking Gear Spoofing Dataset

/var/folders/pw/3vr89zzj1xvbzvtk1yfz9kkc0000gn/T/ipykernel_47040/2115221741.py:41: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data['label'].replace({'R' : 0, 'T' : 1}, inplace = True)
/var/folders/pw/3vr89zzj1xvbzvtk1yfz9kkc0000gn/T/ipykernel_47040/2115221741.py:41: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  data['label'].replace({'R' : 0, 'T' : 1}, inplace = True)

Preprocessing Car Hacking RPM Spoofing Dataset

/var/folders/pw/3vr89zzj1xvbzvtk1yfz9kkc0000gn/T/ipykernel_47040/2115221741.py:41: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data['label'].replace({'R' : 0, 'T' : 1}, inplace = True)
/var/folders/pw/3vr89zzj1xvbzvtk1yfz9kkc0000gn/T/ipykernel_47040/2115221741.py:41: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  data['label'].replace({'R' : 0, 'T' : 1}, inplace = True)

In [6]:
ch_fuzzy_data.head()

      Timestamp    ID  DLC               Payload  label
0  1.478196e+09  1349    8  15564440904897921024      0
1  1.478196e+09   688    5         1097347368265      0
2  1.478196e+09     2    8                 67349      0
3  1.478196e+09   339    8      9307361650868224      0
4  1.478196e+09   304    8   1837469747453560672      0

In [7]:
ch_gear_data.head()

      Timestamp    ID  DLC              Payload  label
0  1.478193e+09   320    8            271133220      0
1  1.478193e+09   704    8  1513209474796486656      0
2  1.478193e+09   848    8   369370384908157054      0
3  1.478193e+09   880    8     9007199254740992      0
4  1.478193e+09  1087    8  1171042553475368960      0

In [8]:
ch_rpm_data.head()

      Timestamp   ID  DLC               Payload  label
0  1.478191e+09  790    8    369972507834318965      0
1  1.478191e+09  399    8  18319235909263556608      0
2  1.478191e+09  608    8   1811047593997725247      0
3  1.478191e+09  672    8   6917673190735133952      0
4  1.478191e+09  809    8  15904600708710662164      0

In [9]:
##Save each of the files as original_file_name_transformed.csv
ch_fuzzy_data.to_csv('Fuzzy_dataset_transformed.csv', index=False)
ch_gear_data.to_csv('gear_dataset_transformed.csv', index=False)
ch_rpm_data.to_csv('RPM_dataset_transformed.csv', index=False)